<a href="https://colab.research.google.com/github/iPranjalSinha/Machine-Learning-Python-Notebooks-/blob/main/6_1_Deep_Learning_Artificial_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part 1: Data preprocessing**

## 1.1. Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.3.0'

## 1.2. Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')

## 1.3. Exploring the dataset

In [ ]:
print(dataset.head())

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]


In [ ]:
print(dataset.shape)

(10000, 14)


In [ ]:
print(dataset.columns)

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')


## 1.4. Identifying independent variables and dependent variables

In [ ]:
# Independent variable
X = dataset.iloc[:, 3:-1].values

# Dependent variable
y = dataset.iloc[:, -1].values

## 1.5. Handling missing data

### 1.5.1. Checking if there is any missing data

In [ ]:
print(dataset.isnull().values.any())

False


### 1.5.2. Handling missing data

In [ ]:
# from sklearn.impute import SimpleImputer
# imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# imputer.fit(X[:, 1:3])
# X[:, 1:3] = imputer.transform(X[:, 1:3])

## 1.6. Encoding categorical data

In [ ]:
# Encoding the 'Gender' column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
# One Hot Encoding the 'Geography' column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

## 1.7. Splitting the dataset into a training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

## 1.8. Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **Part 2: Creating a model**

## 2.1. Building the model

In [ ]:
# Initializing the model
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## 2.2. Compiling the model

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## 2.3. Training the model on the training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 773us/step - loss: 0.5711 - accuracy: 0.7250
Epoch 2/100
250/250 [==============================] - 0s 922us/step - loss: 0.4683 - accuracy: 0.8052
Epoch 3/100
250/250 [==============================] - 0s 772us/step - loss: 0.4398 - accuracy: 0.8134
Epoch 4/100
250/250 [==============================] - 0s 750us/step - loss: 0.4273 - accuracy: 0.8165
Epoch 5/100
250/250 [==============================] - 0s 783us/step - loss: 0.4209 - accuracy: 0.8199
Epoch 6/100
250/250 [==============================] - 0s 820us/step - loss: 0.4161 - accuracy: 0.8234
Epoch 7/100
250/250 [==============================] - 0s 781us/step - loss: 0.4123 - accuracy: 0.8253
Epoch 8/100
250/250 [==============================] - 0s 771us/step - loss: 0.4089 - accuracy: 0.8270
Epoch 9/100
250/250 [==============================] - 0s 724us/step - loss: 0.4058 - accuracy: 0.8281
Epoch 10/100
250/250 [==============================] - 0s 777us/step - l

## 2.2. Predicting the test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## 2.3. Predicting a new result

In [ ]:
# Geography: France
# Credit Score: 600
# Gender: Male
# Age: 40 years old
# Tenure: 3 years
# Balance: $ 60000
# Number of Products: 2
# Does this customer have a credit card? Yes
# Is this customer an Active Member: Yes
# Estimated Salary: $ 50000

ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5

array([[False]])

# **Part 3: Evaluating model's performance**

## 3.1. Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

acc = accuracy_score(y_test, y_pred)
print(acc)

[[1516   69]
 [ 211  204]]
0.86


## 3.2. R-Squared Score


In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.14864505339971856